/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.CatatanController;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Catatan;
import java.util.List;
import javax.swing.JFileChooser;

/**
 *
 * @author LENOVO
 */
public class FrmCatatanHarian extends javax.swing.JFrame {
    
    // Controller untuk menghubungkan Form dengan database melalui DAO
    private CatatanController controller;
    
    // Model tabel untuk mengatur isi tabel (header + baris data)
    private DefaultTableModel model;

    /**
     * Creates new form FrmCatatanHarian
     */
    public FrmCatatanHarian() {
        initComponents();
        controller = new CatatanController();
        setLocationRelativeTo(null);
        
        txtIsi.setLineWrap(true);
        txtIsi.setWrapStyleWord(true);

        // Membuat model tabel beserta nama kolomnya
        model = new DefaultTableModel(
                new Object[]{"No", "Tanggal", "Judul", "Isi Catatan"}, 0
        );
        tblCatatan.setModel(model);  // Menghubungkan model ke JTable

        loadData();  // Memuat data dari database ke tabel saat form dibuka
        
        // Event: ketika baris tabel dipilih, tampilkan datanya ke form input
        tblCatatan.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && tblCatatan.getSelectedRow() != -1) {
                tampilkanDataKeForm();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelUtama = new javax.swing.JPanel();
        JPanelHeader = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        JPanelInput = new javax.swing.JPanel();
        lblTanggal = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        lblJudul2 = new javax.swing.JLabel();
        txtJudul = new javax.swing.JTextField();
        lblIsi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIsi = new javax.swing.JTextArea();
        JPanelButton = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        JPanelCari = new javax.swing.JPanel();
        lblCari = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        JPanelTable = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCatatan = new javax.swing.JTable();
        JPanelButton2 = new javax.swing.JPanel();
        btnExport = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Catatan Harian");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanelUtama.setLayout(new javax.swing.BoxLayout(JPanelUtama, javax.swing.BoxLayout.Y_AXIS));

        JPanelHeader.setBackground(new java.awt.Color(161, 136, 127));
        JPanelHeader.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 10));

        lblJudul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblJudul.setText("APLIKASI CATATAN HARIAN");
        JPanelHeader.add(lblJudul);

        JPanelUtama.add(JPanelHeader);

        JPanelInput.setBackground(new java.awt.Color(215, 204, 200));
        JPanelInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        lblTanggal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTanggal.setText("Tanggal (DD-MM-YYYY) :");

        txtTanggal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblJudul2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJudul2.setText("Judul Catatan                  :");

        txtJudul.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblIsi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIsi.setText("Isi Catatan                       :");

        txtIsi.setColumns(20);
        txtIsi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIsi.setRows(5);
        jScrollPane1.setViewportView(txtIsi);

        javax.swing.GroupLayout JPanelInputLayout = new javax.swing.GroupLayout(JPanelInput);
        JPanelInput.setLayout(JPanelInputLayout);
        JPanelInputLayout.setHorizontalGroup(
            JPanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelInputLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(JPanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTanggal)
                    .addGroup(JPanelInputLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblIsi))
                    .addComponent(lblJudul2))
                .addGap(18, 18, 18)
                .addGroup(JPanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTanggal)
                    .addComponent(txtJudul)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelInputLayout.setVerticalGroup(
            JPanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelInputLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(JPanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTanggal))
                .addGap(18, 18, 18)
                .addGroup(JPanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJudul2)
                    .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(JPanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIsi)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        JPanelUtama.add(JPanelInput);

        JPanelButton.setBackground(new java.awt.Color(188, 170, 164));

        btnTambah.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelButtonLayout = new javax.swing.GroupLayout(JPanelButton);
        JPanelButton.setLayout(JPanelButtonLayout);
        JPanelButtonLayout.setHorizontalGroup(
            JPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelButtonLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelButtonLayout.setVerticalGroup(
            JPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelButtonLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(JPanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnHapus)
                    .addComponent(btnEdit)
                    .addComponent(btnTambah))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        JPanelUtama.add(JPanelButton);

        JPanelCari.setBackground(new java.awt.Color(239, 235, 233));
        JPanelCari.setPreferredSize(new java.awt.Dimension(560, 73));

        lblCari.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCari.setText("Cari Catatan :");

        txtCari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnCari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelCariLayout = new javax.swing.GroupLayout(JPanelCari);
        JPanelCari.setLayout(JPanelCariLayout);
        JPanelCariLayout.setHorizontalGroup(
            JPanelCariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelCariLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblCari)
                .addGap(18, 18, 18)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        JPanelCariLayout.setVerticalGroup(
            JPanelCariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCariLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(JPanelCariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCari)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        JPanelUtama.add(JPanelCari);

        JPanelTable.setBackground(new java.awt.Color(215, 204, 200));

        tblCatatan.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        tblCatatan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Tanggal", "Judul", "Isi Catatan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblCatatan);

        javax.swing.GroupLayout JPanelTableLayout = new javax.swing.GroupLayout(JPanelTable);
        JPanelTable.setLayout(JPanelTableLayout);
        JPanelTableLayout.setHorizontalGroup(
            JPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelTableLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        JPanelTableLayout.setVerticalGroup(
            JPanelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelTableLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        JPanelUtama.add(JPanelTable);

        JPanelButton2.setBackground(new java.awt.Color(188, 170, 164));

        btnExport.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExport.setText("Export");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        btnImport.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnImport.setText("Import");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelButton2Layout = new javax.swing.GroupLayout(JPanelButton2);
        JPanelButton2.setLayout(JPanelButton2Layout);
        JPanelButton2Layout.setHorizontalGroup(
            JPanelButton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelButton2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnImport, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        JPanelButton2Layout.setVerticalGroup(
            JPanelButton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelButton2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(JPanelButton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImport)
                    .addComponent(btnExport))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        JPanelUtama.add(JPanelButton2);

        getContentPane().add(JPanelUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        tambahCatatan();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        editCatatan();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        hapusCatatan();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        cariCatatan();
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        exportCSV();
    }//GEN-LAST:event_btnExportActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        importCSV();
    }//GEN-LAST:event_btnImportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCatatanHarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCatatanHarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCatatanHarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCatatanHarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCatatanHarian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelButton;
    private javax.swing.JPanel JPanelButton2;
    private javax.swing.JPanel JPanelCari;
    private javax.swing.JPanel JPanelHeader;
    private javax.swing.JPanel JPanelInput;
    private javax.swing.JPanel JPanelTable;
    private javax.swing.JPanel JPanelUtama;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnTambah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCari;
    private javax.swing.JLabel lblIsi;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJudul2;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JTable tblCatatan;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextArea txtIsi;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables

    // --- 1. Method load data ke table ---
    private void loadData() {
        model.setRowCount(0);
        List<Catatan> list = controller.getAllCatatan();
        int no = 1;
        for (Catatan c : list) {
            String tanggalTampil = formatTanggalUntukTampilan(c.getTanggal());
            model.addRow(new Object[]{
                no++, c.getTanggal(), c.getJudul(), c.getIsi()
            });
        }
    }
    
    // --- 2. Method tambah catatan ke table ---
    private void tambahCatatan() {
        String tanggal = txtTanggal.getText();
        String judul = txtJudul.getText();
        String isi = txtIsi.getText();
        
        if (tanggal.isEmpty() || judul.isEmpty() || isi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
            return;
        }
        
        try {
            new java.text.SimpleDateFormat("dd-MM-yyyy").setLenient(false);
            new java.text.SimpleDateFormat("dd-MM-yyyy").parse(tanggal);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Format tanggal harus DD-MM-YYYY dan valid!");
            return;
        }
        
        tanggal = formatTanggalUntukDatabase(tanggal);
        
        Catatan c = new Catatan();
        c.setTanggal(tanggal);
        c.setJudul(judul);
        c.setIsi(isi);
        
        if (controller.insertCatatan(c)) {
            JOptionPane.showMessageDialog(this, "Catatan berhasil ditambahkan!");
            loadData();
            clearForm();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menambah catatan!");
        }
    }
    
    // --- 3. Method edit catatan di table ---
    private void editCatatan() {
        int row = tblCatatan.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih catatan yang ingin diedit!");
            return;
        }
        
        String tanggal = txtTanggal.getText();
        String judul = txtJudul.getText();
        String isi = txtIsi.getText();
        
        try {
            new java.text.SimpleDateFormat("dd-MM-yyyy").setLenient(false);
            new java.text.SimpleDateFormat("dd-MM-yyyy").parse(tanggal);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Format tanggal harus DD-MM-YYYY dan valid!");
            return;
        }
        
        tanggal = formatTanggalUntukDatabase(tanggal);
        
        Catatan c = new Catatan();
        c.setId(controller.getAllCatatan().get(row).getId());
        c.setTanggal(tanggal);
        c.setJudul(judul);
        c.setIsi(isi);
        
        if (controller.updateCatatan(c)) {
            JOptionPane.showMessageDialog(this, "Catatan berhasil diperbarui!");
            loadData();
            clearForm();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui catatan!");
        }
    }
    
    // --- 4. Method hapus catatan dari table ---
    private void hapusCatatan() {
        int row = tblCatatan.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih catatan yang ingin dihapus!");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus catatan ini?", "Konfirmasi", JOptionPane.YES_NO_CANCEL_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            int id = controller.getAllCatatan().get(row).getId();
            if (controller.deleteCatatan(id)) {
                JOptionPane.showMessageDialog(this, "Catatan berhasil dihapus!");
                loadData();
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "Gagalmenghapus catatan!");
            }
        }
    }
    
    // --- 5. Method clear form ---
    private void clearForm() {
        txtTanggal.setText("");
        txtJudul.setText("");
        txtIsi.setText("");
        txtCari.setText("");
        tblCatatan.clearSelection();
        
        loadData();
        
        txtTanggal.requestFocus();
    }
    
    // --- 6. Method cari catatan dari table ---
    private void cariCatatan() {
        String keyword = txtCari.getText();
        model.setRowCount(0);
        List<Catatan> list = controller.searchCatatan(keyword);
        int no = 1;
        for (Catatan c : list) {
            model.addRow(new Object[]{
                no++, c.getTanggal(), c.getJudul(), c.getIsi()
            });
        }
    }
    
    // --- 7. Method tampil data dari table ---
    private void tampilkanDataKeForm() {
        int row = tblCatatan.getSelectedRow();
        if (row != -1) {
            String tanggalDB = tblCatatan.getValueAt(row, 1).toString();
            String tanggalTampil = tanggalDB;
            try {
                java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(tanggalDB);
                tanggalTampil = new SimpleDateFormat("dd-MM-yyyy").format(date);
            } catch (Exception e) {}
            
            String judul = tblCatatan.getValueAt(row, 2).toString();
            String isi = tblCatatan.getValueAt(row, 3).toString();
            
            txtTanggal.setText(tanggalTampil);
            txtJudul.setText(judul);
            txtIsi.setText(isi);
        }
    }
    
    // --- 8. Method helper ---
    private String formatTanggalUntukTampilan(String tanggalDB) {
        try {
            java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(tanggalDB);
            return new SimpleDateFormat("dd-MM-yyyy").format(date);
        } catch (ParseException e) {
            return tanggalDB;
        }
    }
    
    private String formatTanggalUntukDatabase(String tanggalTampil) {
        try {
            java.util.Date date = new SimpleDateFormat("dd-MM-yyyy").parse(tanggalTampil);
            return new SimpleDateFormat("yyyy-MM-dd").format(date);
        } catch (ParseException e) {
            return tanggalTampil;
        }
    }
    
    // --- 9. Method export catatan ke CSV ---
    private void exportCSV() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Simpan File CSV");
        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            if (!fileToSave.getAbsolutePath().endsWith(".csv")) {
                fileToSave = new File(fileToSave.getAbsolutePath() + ".csv");
            }

            try (BufferedWriter bw = new BufferedWriter(new FileWriter(fileToSave))) {
                bw.write("Tanggal,Judul,Isi Catatan");
                bw.newLine();

                List<Catatan> list = controller.getAllCatatan();
                for (Catatan c : list) {
                    // Gunakan format tanggal DD-MM-YYYY agar sama dengan tampilan
                    String tglFormatted = formatTanggalUntukTampilan(c.getTanggal());
                    bw.write(String.format("%s,%s,%s",
                        tglFormatted,
                        c.getJudul().replace(",", ";"),   // hindari error CSV
                        c.getIsi().replace(",", ";")));
                    bw.newLine();
                }

                JOptionPane.showMessageDialog(this, "Data berhasil diexport ke " + fileToSave.getAbsolutePath());
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Gagal export data: " + e.getMessage());
            }
        }
    }
    
    // --- 9. Method import dari CSV ---
    private void importCSV() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Pilih File CSV");
        int userSelection = fileChooser.showOpenDialog(this);
        
        if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToOpen = fileChooser.getSelectedFile();
        try (BufferedReader br = new BufferedReader(new FileReader(fileToOpen))) {
            String line;
            boolean firstLine = true;

            while ((line = br.readLine()) != null) {
                if (firstLine) { 
                    firstLine = false; // lewati header
                    continue;
                }

                String[] data = line.split(",", -1);
                if (data.length < 3) continue;

                String tanggal = data[0].trim();
                String judul = data[1].trim();
                String isi = data[2].trim();

                // Konversi format tanggal ke format database
                tanggal = formatTanggalUntukDatabase(tanggal);

                Catatan c = new Catatan();
                c.setTanggal(tanggal);
                c.setJudul(judul);
                c.setIsi(isi);

                controller.insertCatatan(c);
            }

                JOptionPane.showMessageDialog(this, "Data berhasil diimport dari " + fileToOpen.getName());
                loadData(); // refresh tabel
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Gagal import data: " + e.getMessage());
            }
        }
    }
}
